Gem::Specification.new do |s|
  s.name        = 'neutrino_api'
  s.version     = '3.2.5'
  s.summary     = 'neutrino_api'
  s.description = 'This API SDK was automatically generated by APIMATIC Beta 2.0'
  s.authors     = ["APIMATIC", "Zeeshan Ejaz Bhatti"]
  s.email       = 'zeeshan@apimatic.io'
  s.homepage    = 'https://apimatic.io'
  s.license     = 'MIT'
  
  s.add_dependency('unirest', '~> 1.1.2')
  s.required_ruby_version = '~> 2.0'

  s.files       = Dir['{bin,lib,man,test,spec}/**/*', 'README*', 'LICENSE*']  
  s.require_paths = ['lib']
  
end